# Generated by Django 3.2.9 on 2022-12-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureses',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
