# Generated by Django 3.2.9 on 2022-12-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221207_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/img/'),
        ),
    ]
