# Generated by Django 3.2.9 on 2022-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coureses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
