# Generated by Django 3.2.9 on 2022-12-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_articles_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coureses',
            name='komu_podhodit',
        ),
        migrations.RemoveField(
            model_name='coureses',
            name='komu_podhodit_1',
        ),
        migrations.RemoveField(
            model_name='coureses',
            name='komu_podhodit_text',
        ),
        migrations.RemoveField(
            model_name='coureses',
            name='komu_podhodit_text_1',
        ),
        migrations.AddField(
            model_name='coureses',
            name='suitable_for_whom_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кому подходит 1'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='suitable_for_whom_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кому подходит 2'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='suitable_for_whom_text_1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Кому подходит текст 1'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='suitable_for_whom_text_2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Кому подходит текст 2'),
        ),
    ]
