# Generated by Django 3.2.9 on 2022-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20221208_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureses',
            name='suitable_for_whom_1',
            field=models.CharField(blank=True, default='Новичкам', max_length=100, null=True, verbose_name='Кому подходит 1'),
        ),
        migrations.AlterField(
            model_name='coureses',
            name='suitable_for_whom_2',
            field=models.CharField(blank=True, default='Новичкам', max_length=100, null=True, verbose_name='Кому подходит 2'),
        ),
    ]
