# Generated by Django 3.2.9 on 2022-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221208_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureses',
            name='detail_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Детальное название'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='detail_title_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст в деталях'),
        ),
    ]
