# Generated by Django 3.2.9 on 2022-12-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221211_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coureses',
            name='text_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Что дает профессия 1'),
        ),
        migrations.AlterField(
            model_name='coureses',
            name='text_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Что дает профессия 2'),
        ),
        migrations.AlterField(
            model_name='coureses',
            name='text_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Что дает профессия 3'),
        ),
    ]
