# Generated by Django 3.2.9 on 2022-12-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221211_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='disadvantage_1',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Недостаток-1'),
        ),
        migrations.AddField(
            model_name='articles',
            name='disadvantage_2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Недостаток-2'),
        ),
        migrations.AddField(
            model_name='articles',
            name='disadvantage_3',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Недостаток-3'),
        ),
    ]
