# Generated by Django 3.2.9 on 2022-12-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20221214_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureses',
            name='course_href',
            field=models.TextField(blank=True, null=True, verbose_name='сслыка'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='start_time',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='С какого времени работает'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_1',
            field=models.TextField(blank=True, null=True, verbose_name='о языке'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='full_text_2',
            field=models.TextField(blank=True, null=True, verbose_name='текст под заголовкам'),
        ),
    ]
