# Generated by Django 3.2.9 on 2022-12-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221215_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='coureses',
            name='person_href_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на первого'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='person_href_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на второго'),
        ),
        migrations.AddField(
            model_name='coureses',
            name='person_href_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка на третьего'),
        ),
    ]
