# Generated by Django 3.2.9 on 2022-12-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20221216_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aja_look',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/img/')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
