# Generated by Django 3.2.9 on 2022-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_aja_look'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='advantage_1',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Примущество-1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='advantage_2',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Примущество-2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='advantage_3',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Примущество-3'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='disadvantage_1',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Недостаток-1'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='disadvantage_2',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Недостаток-2'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='disadvantage_3',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Недостаток-3'),
        ),
    ]
